### ISSUE TITLE
Ability to create JS/TS task function boilerplate

### ISSUE THREAD

**Issue by christopherhex** [ExtraHorizon/exh-cli#6]
the task service expects the task code file to be in a certain format, with a specific function name etc,... 
Would be helpful if the cli contains a function to setup the boilerplate for a task with all the necessary files. 

Looking at https://github.com/ExtraHorizon/sleepMonitoringDemo/tree/master/tasks/sleepFileProcessingTask, 
we could create a boilerplate that includes:
* `package.json` file
* `tsconfig.json` file 
* `src/index.ts` file that includes default function structure

**Comment by FilipAben** [comment]
Small remark: the function name is not fixed, you can specify the name when creating a task.

**Comment by FilipAben** [comment]
I propose that we make a public template task repository on Github. The client can then clone this repo, remove the remote + do some managerial things like setting the task name. The advantage of this approach is that the template will be easier to maintain in terms of updates/dependencies.

**Comment by christopherhex** [comment]
Moved to [EXHCLI-1](https://qompium.atlassian.net/browse/EXHCLI-1)
