### ISSUE TITLE
Task creation - include zipping and base-64 of code in cli tool

### ISSUE THREAD

**Issue by christopherhex** [ExtraHorizon/exh-cli#8]
`exh tasks create` has a `--code` option which expects a base64-encoded string containing the zip file that includes the content of the task. The base64 encoding and zipping is up to the user today. 

Would be more convenient if the cli tool is able to detect that a directory is being passed along, and the cli tool then does the zipping and base-64 encoding.

**Comment by FilipAben** [comment]
Note: base-64 encoding is done already, just the zipping needs to be done
